### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Wertzui123** [BlockHorizons/InvSee#18] opened 2019-04-28 18:31 UTC
[19:56:39] [Server thread/CRITICAL]: InvalidStateException: "Tried to schedule task to disabled scheduler" (EXCEPTION) in "src/pocketmine/scheduler/TaskScheduler" at line 148

**Comment by Muqsit** [comment] 2019-04-28 19:37
Duplicate of #8

**Closed as completed by Muqsit** 2019-04-28 19:37 UTC
Labels: duplicate

**Comment by Wertzui123** [comment] 2019-04-28 21:48
Come on, just fix it...
