### ISSUE TITLE
Plugin no longer works

### ISSUE THREAD

**Issue by Eren-Alexis-Dreamuur** [BlockHorizons/InvSee#32] opened 2020-12-07 01:30 UTC
Error: "Class 'muqsit\invmenu\InvMenuHandler' not found" (EXCEPTION) in "plugins/InvSee-master/src/BlockHorizons/InvSee/InventoryHandler" at line 27
[01:15:51] [Server thread/CRITICAL]: #0 plugins/InvSee-master/src/BlockHorizons/InvSee/Loader(14): BlockHorizons\InvSee\InventoryHandler->__construct(object BlockHorizons\InvSee\Loader)
[01:15:51] [Server thread/CRITICAL]: #1 src/pocketmine/plugin/PluginBase(116): BlockHorizons\InvSee\Loader->onEnable()
[01:15:51] [Server thread/CRITICAL]: #2 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[01:15:51] [Server thread/CRITICAL]: #3 src/pocketmine/Server(1787): pocketmine\plugin\PluginManager->enablePlugin(object BlockHorizons\InvSee\Loader)
[01:15:51] [Server thread/CRITICAL]: #4 src/pocketmine/Server(1773): pocketmine\Server->enablePlugin(object BlockHorizons\InvSee\Loader)
[01:15:51] [Server thread/CRITICAL]: #5 src/pocketmine/Server(1586): pocketmine\Server->enablePlugins(integer 1)
[01:15:51] [Server thread/CRITICAL]: #6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[01:15:51] [Server thread/CRITICAL]: #7 src/pocketmine/PocketMine(304): pocketmine\server()
[01:15:51] [Server thread/CRITICAL]: #8 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

even though i reset the server it didnt work

**Comment by Muqsit** [comment] 2020-12-07 02:42
Duplicate of #1

**Closed as completed by Muqsit** 2020-12-07 02:42 UTC
Labels: duplicate
