### ISSUE TITLE
InvalidStateException: "Tried to schedule task to disabled scheduler" (EXCEPTION) in "src/pocketmine/scheduler/TaskScheduler" at line 148

### ISSUE THREAD

**Issue by teracube** [BlockHorizons/InvSee#19] opened 2019-06-13 06:59 UTC
https://poggit.pmmp.io/r/51217/InvSee_dev-13.phar
https://jenkins.pmmp.io/job/PocketMine-MP/1765/artifact/PocketMine-MP.phar

```
2019-06-12 [20:01:27] [Server thread/INFO]: [Commandlook] skyfox 176> /invsee monster123
2019-06-12 [20:01:27] [Server thread/CRITICAL]: InvalidStateException: "Tried to schedule task to disabled scheduler" (EXCEPTION) in "src/pocketmine/scheduler/TaskScheduler" at line 148
2019-06-12 [20:01:27] [Server thread/DEBUG]: #0 src/pocketmine/scheduler/TaskScheduler(80): pocketmine\scheduler\TaskScheduler->addTask(object BlockHorizons\InvSee\libs\muqsit\invmenu\tasks\DelayedFakeBlockDataNotifyTask, integer 5, integer -1)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #1 plugins/InvSee_dev-13.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/inventories/BaseFakeInventory(122): pocketmine\scheduler\TaskScheduler->scheduleDelayedTask(object BlockHorizons\InvSee\libs\muqsit\invmenu\tasks\DelayedFakeBlockDataNotifyTask, integer 5)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #2 plugins/InvSee_dev-13.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/inventories/DoubleChestInventory(62): BlockHorizons\InvSee\libs\muqsit\invmenu\inventories\BaseFakeInventory->onFakeBlockDataSend(object pocketmine\Player)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #3 plugins/InvSee_dev-13.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/inventories/BaseFakeInventory(65): BlockHorizons\InvSee\libs\muqsit\invmenu\inventories\DoubleChestInventory->sendFakeBlockData(object pocketmine\Player, object BlockHorizons\InvSee\libs\muqsit\invmenu\utils\HolderData)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #4 plugins/InvSee_dev-13.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/InvMenu(115): BlockHorizons\InvSee\libs\muqsit\invmenu\inventories\BaseFakeInventory->send(object pocketmine\Player, string[27] monster123's Inventory)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #5 plugins/InvSee_dev-13.phar/src/BlockHorizons/InvSee/InventoryHandler(92): BlockHorizons\InvSee\libs\muqsit\invmenu\InvMenu->send(object pocketmine\Player)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #6 plugins/InvSee_dev-13.phar/src/BlockHorizons/InvSee/commands/InvSeeCommand(20): BlockHorizons\InvSee\InventoryHandler->send(object pocketmine\Player, string[15] monster123, string[54] BlockHorizons\InvSee\inventories\InvSeePlayerInventory)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #7 plugins/InvSee_dev-13.phar/src/BlockHorizons/InvSee/commands/BaseCommand(114): BlockHorizons\InvSee\commands\InvSeeCommand->onCommand(object pocketmine\Player, string[6] invsee, array[1])
2019-06-12 [20:01:27] [Server thread/DEBUG]: #8 src/pocketmine/command/SimpleCommandMap(270): BlockHorizons\InvSee\commands\BaseCommand->execute(object pocketmine\Player, string[6] invsee, array[1])
2019-06-12 [20:01:27] [Server thread/DEBUG]: #9 src/pocketmine/Server(2019): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[22] invsee monster123)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #10 src/pocketmine/Player(2231): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[22] invsee monster123)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(240): pocketmine\Player->chat(string[23] /invsee monster123)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #14 src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #16 src/pocketmine/Player(3124): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #17 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #18 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 91.XXX.XXX.79 58555, object raklib\protocol\EncapsulatedPacket, integer 0)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #19 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #20 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #21 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #22 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #23 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1560362487.3302)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #24 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #25 src/pocketmine/Server(1774): pocketmine\Server->start()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #26 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[34] /teracube/, string[42] /teracube/plugins/)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #27 (1): require(string[89] phar:///teracube/PocketMine-MP.phar/src/pocketmine/Pocke)
2019-06-12 [20:01:27] [Server thread/INFO]: skyfox 176 [-]
2019-06-12 [20:01:27] [Server thread/CRITICAL]: Could not save player "skyfox 176": file_put_contents(/teracube/players/skyfox 176.dat): failed to open stream: Permission denied
2019-06-12 [20:01:27] [Server thread/CRITICAL]: ErrorException: "file_put_contents(/teracube/players/skyfox 176.dat): failed to open stream: Permission denied" (EXCEPTION) in "src/pocketmine/Server" at line 886
2019-06-12 [20:01:27] [Server thread/DEBUG]: #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[116] file_put_contents(/teracube/players/skyfox 176.dat): fail, string[85] phar:///teracube/PocketMine-MP.phar/src/pocketmine/Serve, integer 886, array[4])
2019-06-12 [20:01:27] [Server thread/DEBUG]: #1 src/pocketmine/Server(886): file_put_contents(string[55] /teracube/players/skyfox 176.dat, string[6886] .............xV...oHXEe..,.T.mA6A."A6..E....._ o%5$...W...U..UkUT.PV.}.aK.N.. nu)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #2 src/pocketmine/Player(3615): pocketmine\Server->saveOfflinePlayerData(string[9] skyfox 176, object pocketmine\nbt\tag\CompoundTag)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #3 src/pocketmine/Player(3501): pocketmine\Player->save()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #4 src/pocketmine/network/mcpe/RakLibInterface(176): pocketmine\Player->close(object pocketmine\lang\TranslationContainer, string[21] Internal server error)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #5 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 91.XXX.XXX.79 58555, object raklib\protocol\EncapsulatedPacket, integer 0)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #8 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #9 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #10 src/pocketmine/Server(2338): pocketmine\snooze\SleeperHandler->sleepUntil(double 1560362487.3302)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #11 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #12 src/pocketmine/Server(1774): pocketmine\Server->start()
2019-06-12 [20:01:27] [Server thread/DEBUG]: #13 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[34] /teracube/, string[42] /teracube/plugins/)
2019-06-12 [20:01:27] [Server thread/DEBUG]: #14 (1): require(string[89] phar:///teracube/PocketMine-MP.phar/src/pocketmine/Pocke)
2019-06-12 [20:01:27] [Server thread/INFO]: skyfox 176[/91.XXX.XXX.79:58555] logged out due to Internal server error
2019-06-12 [20:01:27] [RakLibServer thread/NOTICE]: Blocked 91.XXX.XXX.79 for 5 seconds
```

**Comment by lukeeey** [comment] 2019-06-13 13:04
Can i just point out that the server doesnt seem to have permission to save your player data to a file. Thats not ideal.

**Comment by teracube** [comment] 2019-06-13 16:16
@lukeeey 
permision denied only for this player.. i don't know why...
no problem with other players

**Comment by Muqsit** [comment] 2019-06-22 17:13
Duplicate of #8

**Closed as completed by Muqsit** 2019-06-22 17:13 UTC
Labels: duplicate
