### ISSUE TITLE
fix pls

### ISSUE THREAD

**Issue by CatalizCS** [BlockHorizons/InvSee#20] opened 2019-06-22 15:54 UTC
2019-06-22 [15:51:57] [Server thread/CRITICAL]: Error: "Class 'muqsit\invmenu\InvMenuHandler' not found" (EXCEPTION) in "plugins/InvSee-master/src/BlockHorizons/InvSee/InventoryHandler" at line 27
2019-06-22 [15:51:57] [Server thread/DEBUG]: #0 plugins/InvSee-master/src/BlockHorizons/InvSee/Loader(14): BlockHorizons\InvSee\InventoryHandler->__construct(object BlockHorizons\InvSee\Loader)
2019-06-22 [15:51:57] [Server thread/DEBUG]: #1 src/pocketmine/plugin/PluginBase(123): BlockHorizons\InvSee\Loader->onEnable()
2019-06-22 [15:51:57] [Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(588): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
2019-06-22 [15:51:57] [Server thread/DEBUG]: #3 src/pocketmine/Server(1992): pocketmine\plugin\PluginManager->enablePlugin(object BlockHorizons\InvSee\Loader)
2019-06-22 [15:51:57] [Server thread/DEBUG]: #4 src/pocketmine/Server(1978): pocketmine\Server->enablePlugin(object BlockHorizons\InvSee\Loader)
2019-06-22 [15:51:57] [Server thread/DEBUG]: #5 src/pocketmine/Server(1772): pocketmine\Server->enablePlugins(integer 1)
2019-06-22 [15:51:57] [Server thread/DEBUG]: #6 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[40] C:\Users\Administrator\Desktop\Skyblock\, string[48] C:\Users\Administrator\Desktop\Skyblock\plugins\)
2019-06-22 [15:51:57] [Server thread/DEBUG]: #7 (1): require(string[95] phar://C:/Users/Administrator/Desktop/Skyblock/PocketMine-MP.phar/src/pocketmine)
2019-06-22 [15:51:57] [Server thread/INFO]: Disabling InvSee v1.0.0

**Comment by Muqsit** [comment] 2019-06-22 17:14
Duplicate of #4

**Closed as completed by Muqsit** 2019-06-22 17:14 UTC
